name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: clang-tidy review
      # You may pin to the exact commit or the version.
      # uses: ZedThree/clang-tidy-review@33e015025bb38c888d54b66bb97ca7c81c259436
      uses: ZedThree/clang-tidy-review@v0.4.0
      with:
        # Authentication token
        token: # optional, default is ${{ github.token }}
        # Directory containing the compile_commands.json file
        build_dir: # optional, default is .
        # Version of clang-tidy to use; one of 6.0, 7, 8, 9, 10
        clang_tidy_version: # optional, default is 10
        # List of checks
        clang_tidy_checks: # optional, default is -*,performance-*,readability-*,bugprone-*,clang-analyzer-*,cppcoreguidelines-*,mpi-*,misc-*
        # Comma-separated list of files or patterns to include
        include: # optional, default is "*.[ch],*.[ch]xx,*.[ch]pp,*.[ch]++,*.cc,*.hh"
        # Comma-separated list of files or patterns to exclude
        exclude: # optional, default is 
        # Comma-separated list of apt packages to install
        apt_packages: # optional, default is 
        # Maximum number of comments to post at once
        max_comments: # optional, default is 25
        # 
        pr: # optional, default is ${{ github.event.pull_request.number }}
        # 
        repo: # optional, default is ${{ github.repository }}
